image: "python:3"

stages:
  - build
  - test

check-compiler:
  stage: .pre
  script:
    - "gcc --version"


build-c:
  stage: build
  script:
    - "cd R2U2_SW/R2U2_C"
    - "make"

test-parser:
  stage: test
  script:
    - "cd tools/Compiler"
    - "python3 MLTL_parser_test.py"

test-ft-and-pt-reports:
  stage: test
  script: 
    - "cd R2U2_SW/R2U2_C"
    - "make"
    - "cd ../.."
    - "cd test"
    - "python3 LargeFtSubset.py -r c"
    - "python3 LargeFtSubset.py -v c"
