image: "python:3"

before_script:
  - "gcc --version"
  - "python --version"
  - "pip install antlr4-python3-runtime numpy"
  # - "apt update && apt -y install libfftw3-dev"

stages:
  - test

ft-test:
  stage: test
  script:
    - "cd R2U2_C"
    - "make"
    - "cd ../test/TL_formula/"
    - "python3 genFormulas.py -m"
    - "cd ../Inputs"
    - "python3 genInputs.py -m"
    - "cd ../Oracle"
    - "python3 genOracle.py -m"
    - "cd .."
    - "python3 Subset/FT_Subset.py -r c"
    - "python3 Subset/FT_Subset.py -v c"
    - "python3 Report/FT_Report.py"

large-ft-test:
  stage: test
  script:
    - "cd R2U2_C"
    - "make"
    - "cd ../test/TL_formula/"
    - "python3 genFormulas.py -m"
    - "cd ../Inputs"
    - "python3 genInputs.py -m"
    - "cd ../Oracle"
    - "python3 genOracle.py -m"
    - "cd .."
    - "python3 Subset/LargeFtSubset.py -r c"
    - "python3 Subset/LargeFtSubset.py -v c"
    - "python3 Report/LargeFtReport.py"

large-pt-test:
  stage: test
  script:
    - "cd R2U2_C"
    - "make"
    - "cd ../test/TL_formula/"
    - "python3 genFormulas.py -m"
    - "cd ../Inputs"
    - "python3 genInputs.py -m"
    - "cd ../Oracle"
    - "python3 genOracle.py -m"
    - "cd .."
    - "python3 Subset/LargePtSubset.py -r c"
    - "python3 Subset/LargePtSubset.py -v c"
    - "python3 Report/LargePtReport.py"

ft-pt-test:
  stage: test
  script:
    - "cd R2U2_C"
    - "make"
    - "cd ../test/TL_formula/"
    - "python3 genFormulas.py -m"
    - "cd ../Inputs"
    - "python3 genInputs.py -m"
    - "cd ../Oracle"
    - "python3 genOracle.py -m"
    - "cd .."
    - "python3 Subset/FT_PT_Subset.py -r c"
    - "python3 Subset/FT_PT_Subset.py -v c"
    - "python3 Report/FT_PT_Report.py"
