image: "python:3"

before_script:
  - "gcc --version"
  - "python --version"
  - "pip install antlr4-python3-runtime numpy"
  # - "apt update && apt -y install libfftw3-dev"

stages:
  - test

cav-test:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python r2u2test.py ../compiler/r2u2prep.py ../monitors/static/build/r2u2 cav"

long-trace:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python r2u2test.py ../compiler/r2u2prep.py ../monitors/static/build/r2u2 long_trace"

ft-pt-test:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python r2u2test.py ../compiler/r2u2prep.py ../monitors/static/build/r2u2 regression"
