image: "python:3"

before_script:
  - "gcc --version"
  - "python --version"
  - "pip install antlr4-python3-runtime numpy"
  - "apt update && apt -y install libfftw3-dev"

stages:
  - test

test-ft-report:
  stage: test
  script:
    - "cd R2U2_SW/R2U2_C"
    - "make"
    - "cd ../../test/TL_formula/"
    - "python3 genFormulas.py -m"
    - "cd ../Inputs"
    - "python3 genInputs.py -m"
    - "cd ../Oracle"
    - "python3 genOracle.py -m"
    - "cd .."
    - "python3 LargeFtSubset.py -r c"
    - "python3 LargeFtSubset.py -v c"
    - "python3 LargeFtReport.py"

test-pt-report:
  stage: test
  script:
    - "cd R2U2_SW/R2U2_C"
    - "make"
    - "cd ../../test/TL_formula/"
    - "python3 genFormulas.py -m"
    - "cd ../Inputs"
    - "python3 genInputs.py -m"
    - "cd ../Oracle"
    - "python3 genOracle.py -m"
    - "cd .."
    - "python3 LargePtSubset.py -r c"
    - "python3 LargePtSubset.py -v c"
    - "python3 LargePtReport.py"
