image: "python:3"

before_script:
  - "gcc --version"
  - "python3 --version"
  - "apt update && apt -y install z3"
  - "cd compiler"
  - "sh setup_egglog.sh"
  # - "apt update && apt -y install libfftw3-dev"

stages:
  - test

c2po-test:
  stage: test
  script:
    - "cd compiler/test"
    - "python3 test.py"

cav-test:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static/build/r2u2 cav"

long-trace:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static/build/r2u2 long_trace"

ft-subset:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static/build/r2u2 ft_subset"

ft-pt-test:
  stage: test
  script:
    - "cd monitors/static"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static/build/r2u2 regression"
