image: "python:3"

stages:
  - build
  - test

check-compiler:
  stage: .pre
  script:
    - "gcc --version"


build-c:
  stage: build
  script:
    - "cd R2U2_SW/R2U2_C"
    - "make"

test-parser:
  stage: test
  script:
    - "cd tools/Compiler"
    - "python3 MLTL_parser_test.py"
