image: "python:3"

before_script:
  - "gcc --version"
  - "python3 --version"
  - "apt update && apt -y install z3"

stages:
  - test

c2po-test:
  stage: test
  script:
    - "cd compiler/test"
    - "python3 test.py"

cav-test-c:
  stage: test
  script:
    - "cd monitors/static_c"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static_c/build/r2u2 cav"

# cav-test-rust:
#   stage: test
#   script:
#     - "cd test"
#     - "python3 r2u2test.py --c2po ../compiler/c2po.py --monitor static_rust cav"

long-trace-c:
  stage: test
  script:
    - "cd monitors/static_c"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static_c/build/r2u2 long_trace"

ft-subset-c:
  stage: test
  script:
    - "cd monitors/static_c"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static_c/build/r2u2 ft_subset"

# ft-subset-rust:
#   stage: test
#   script:
#     - "cd test"
#     - "python3 r2u2test.py --c2po ../compiler/c2po.py --monitor static_rust ft_subset"

ft-pt-test-c:
  stage: test
  script:
    - "cd monitors/static_c"
    - "make"
    - "cd ../../test"
    - "python3 r2u2test.py --c2po ../compiler/c2po.py --r2u2bin ../monitors/static_c/build/r2u2 regression"
