# This file was generated by Cursor AI on 2026-04-21.

FROM ubuntu:24.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV DEBIAN_FRONTEND=noninteractive


# Install system dependencies used by the Apptainer image.
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    git \
    curl \
    wget \
    unzip \
    build-essential \
    ca-certificates \
    parallel \
    locales \
    patch \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Configure locale to suppress Perl warnings.
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen en_US.UTF-8

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8

# Install Rust toolchain.
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Keep all paths and env vars from the Apptainer environment section.
ENV PATH=/opt/z3/bin:/opt/egglog/target/release:/opt/egglog-experimental/target/release:/root/.cargo/bin:/opt/venv/bin:/opt/cvc5/bin:$PATH
ENV VIRTUAL_ENV=/opt/venv
ENV GRB_LICENSE_FILE=/root/gurobi.lic
ENV PYTHONPATH=/opt/compiler

RUN mkdir -p /opt/benchmarks

# Benchmark corpus used by the benchmarks.txt generator (same filters as find below).
COPY benchmarks/boeing-wbs /opt/benchmarks/boeing-wbs
COPY benchmarks/nasa-atc /opt/benchmarks/nasa-atc
COPY benchmarks/mtl-patterns /opt/benchmarks/mtl-patterns
COPY benchmarks/mavlink /opt/benchmarks/mavlink
COPY benchmarks/fluxgate /opt/benchmarks/fluxgate
COPY benchmarks/utm /opt/benchmarks/utm

# Paper results for the eqsat benchmarks.
COPY benchmarks/scripts/eqsat/paper-results /opt/benchmarks/paper-results
RUN mkdir -p /opt/benchmarks/results

# Compiler tree at /opt/compiler so PROJECT_ROOT=/opt resolves compiler/c2po.py in benchmark.sh.
COPY compiler /opt/compiler

COPY benchmarks/scripts/eqsat/benchmark.sh /opt/benchmarks/scripts/benchmark.sh
RUN sed -i 's|^PROJECT_ROOT=.*|PROJECT_ROOT="/opt/"|' /opt/benchmarks/scripts/benchmark.sh

# Generate absolute benchmark file list.
RUN mkdir -p /opt/benchmarks/benchmarks && \
    : > /opt/benchmarks/benchmarks.txt && \
    while IFS= read -r file; do \
        case "${file}" in \
            */boeing-wbs/*.c2po) echo "${file}" >> /opt/benchmarks/benchmarks.txt ;; \
            */nasa-atc/*.c2po) echo "${file}" >> /opt/benchmarks/benchmarks.txt ;; \
            */mtl-patterns/*.mltl) echo "${file}" >> /opt/benchmarks/benchmarks.txt ;; \
            *.mltl) echo "${file}" >> /opt/benchmarks/benchmarks.txt ;; \
        esac; \
    done < <(find /opt/benchmarks/ -type f \( -name '*.mltl' -o -name '*.c2po' \) | sort)

COPY benchmarks/scripts/eqsat/run-scripts /opt/benchmarks/scripts
RUN chmod +x /opt/benchmarks/scripts/*.sh

# Move rewrites directory to /opt/rewrites
RUN mv /opt/compiler/scripts/rewrites /opt/rewrites
RUN cp /opt/compiler/scripts/prove.sh /opt/rewrites/prove.sh
RUN chmod +x /opt/rewrites/generate_egglog_and_prove.sh

# Install z3.
RUN mkdir -p /opt/z3 && \
    cd /opt/z3 && \
    wget https://github.com/Z3Prover/z3/releases/download/z3-4.15.0/z3-4.15.0-x64-glibc-2.39.zip && \
    unzip z3-4.15.0-x64-glibc-2.39.zip && \
    rm z3-4.15.0-x64-glibc-2.39.zip && \
    cp -r z3-4.15.0-x64-glibc-2.39/* . && \
    rm -rf z3-4.15.0-x64-glibc-2.39 && \
    chmod +x /opt/z3/bin/z3

# Install cvc5.
RUN cd /opt/ && \
    wget https://github.com/cvc5/cvc5/releases/download/cvc5-1.3.3/cvc5-Linux-x86_64-static.zip && \
    unzip cvc5-Linux-x86_64-static.zip && \
    rm cvc5-Linux-x86_64-static.zip && \
    mv cvc5-Linux-x86_64-static cvc5 && \
    chmod +x /opt/cvc5/bin/cvc5

# Build egglog.
RUN mkdir -p /opt/egglog && \
    cd /opt/egglog && \
    git clone https://github.com/egraphs-good/egglog.git . && \
    git checkout v2.0.0 && \
    if [ -f /opt/compiler/scripts/egglog.patch ]; then patch -p1 < /opt/compiler/scripts/egglog.patch; fi && \
    cargo build --bin egglog --release

# Build egglog-experimental.
RUN mkdir -p /opt/egglog-experimental && \
    cd /opt/egglog-experimental && \
    git clone https://github.com/egraphs-good/egglog-experimental.git . && \
    git checkout 38b3898 && \
    if [ -f /opt/compiler/scripts/egglog_experimental.patch ]; then patch -p1 < /opt/compiler/scripts/egglog_experimental.patch; fi && \
    cargo build --bin egglog-experimental --release

# Create Python virtual environment and install gurobi Python package.
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir gurobipy==12.0.3


# License should be mounted to /root/gurobi.lic at runtime.
RUN mkdir -p /root

WORKDIR /opt/
