#!/usr/bin/env python3
"""Generate Markdown documentation for all registered C2PO commands.

This file was generated by Cursor AI on 2026-04-14.
"""

from __future__ import annotations

import argparse
import collections
import datetime
import inspect
import pathlib
import re
import subprocess
import sys
from typing import Any, Mapping


def _format_option_default(option: Mapping[str, Any]) -> str:
    default = option.get("default")
    if default is None:
        return "none"
    return f"`{default}`"


def _format_option_type(option: Mapping[str, Any]) -> str:
    option_type = option.get("type")
    if option_type is None:
        return "unknown"
    return getattr(option_type, "__name__", str(option_type))


def _command_source_file(command: Any) -> str:
    source_file = inspect.getsourcefile(command.func)
    if source_file is None:
        return "unknown"
    return pathlib.Path(source_file).name


def build_markdown() -> str:
    # Ensure local imports resolve whether this script is run from repo root
    # or from within compiler/scripts.
    script_path = pathlib.Path(__file__).resolve()
    compiler_dir = script_path.parents[1]
    if str(compiler_dir) not in sys.path:
        sys.path.insert(0, str(compiler_dir))

    # Import main to trigger command registration side effects.
    import c2po.main  # noqa: F401
    from c2po.command import CommandRegistry, CompositeCommand

    today = datetime.date.today().isoformat()
    lines: list[str] = [
        "# C2PO Commands Reference",
        "",
        f"_Auto-generated on {today} by `compiler/scripts/generate_commands_doc.py`._",
        "",
        f"Total commands: **{len(CommandRegistry.commands)}**",
        "",
    ]

    commands_by_file: dict[str, list[Any]] = collections.defaultdict(list)
    for command in CommandRegistry.commands:
        commands_by_file[_command_source_file(command)].append(command)

    for source_file in sorted(commands_by_file):
        lines.extend([f"## Source: `{source_file}`", ""])
        for command in commands_by_file[source_file]:
            lines.extend(
                [
                    f"### `{command.name}`",
                    "",
                    command.description,
                    "",
                    "```text",
                    command.argparser.format_usage().strip(),
                    "```",
                    "",
                ]
            )

            if isinstance(command, CompositeCommand):
                lines.append("#### Commands included in this composite command")
                lines.append("")
                for subcommand in command.commands:
                    lines.append(f"- `{subcommand.name}`")
                lines.append("")

            if command.options:
                lines.append("#### Options")
                lines.append("")
                for option in command.options:
                    option_name = option["name"]
                    required = "required" if option["required"] else "optional"
                    option_type = _format_option_type(option)
                    default = _format_option_default(option)
                    choices = option.get("choices")
                    choice_text = (
                        f", choices: `{', '.join(str(v) for v in choices)}`"
                        if choices
                        else ""
                    )
                    lines.append(
                        f"- `{option_name}` ({required}, type: `{option_type}`, default: {default}{choice_text}) - {option['description']}"
                    )
                lines.append("")
            else:
                lines.extend(["No options.", ""])

    return "\n".join(lines).rstrip() + "\n"


def _extract_help_sections(help_text: str) -> tuple[str, list[str], list[str]]:
    lines = help_text.splitlines()
    usage_lines: list[str] = []
    positional_lines: list[str] = []
    option_lines: list[str] = []

    section = "usage"
    for line in lines:
        stripped = line.strip()

        if stripped == "positional arguments:":
            section = "positional"
            continue
        if stripped == "options:":
            section = "options"
            continue

        if section == "usage":
            usage_lines.append(line)
        elif section == "positional":
            if line.strip():
                positional_lines.append(line.rstrip())
        elif section == "options":
            if line.strip():
                option_lines.append(line.rstrip())

    usage_text = "\n".join(usage_lines).rstrip()
    return usage_text, positional_lines, option_lines


def _format_argument_section(section_lines: list[str], is_options: bool) -> list[str]:
    grouped_lines: list[list[str]] = []
    current_group: list[str] = []

    for line in section_lines:
        if not line.strip():
            continue

        starts_new = (
            line.startswith("  -") or line.startswith("  --")
            if is_options
            else line.startswith("  ") and not line.startswith("    ")
        )

        if starts_new:
            if current_group:
                grouped_lines.append(current_group)
            current_group = [line.strip()]
        elif current_group:
            current_group.append(line.strip())

    if current_group:
        grouped_lines.append(current_group)

    formatted_items: list[str] = []
    for group in grouped_lines:
        first_line = group[0]
        match = re.match(r"^(?P<name>\S.*?)(?:\s{2,}(?P<desc>.*))?$", first_line)
        if match is None:
            name = first_line
            description_parts = group[1:]
        else:
            name = match.group("name")
            description_parts = []
            first_description = match.group("desc")
            if first_description:
                description_parts.append(first_description.strip())
            description_parts.extend(group[1:])

        description = " ".join(part.strip() for part in description_parts if part.strip())
        if description:
            formatted_items.append(f"- `{name}` - {description}")
        else:
            formatted_items.append(f"- `{name}`")

    return formatted_items


def build_options_markdown() -> str:
    script_path = pathlib.Path(__file__).resolve()
    compiler_dir = script_path.parents[1]
    c2po_script = compiler_dir / "c2po.py"

    help_proc = subprocess.run(
        [sys.executable, str(c2po_script), "--help"],
        cwd=str(compiler_dir),
        capture_output=True,
        text=True,
        check=True,
    )
    usage_text, positional_lines, option_lines = _extract_help_sections(help_proc.stdout)

    lines: list[str] = [
        "# CLI Options",
        "",
        "The following options are generated from `python3 c2po.py --help`:",
        "",
        "```text",
        usage_text,
        "```",
        "",
        "## Positional Arguments",
        "",
    ]

    if positional_lines:
        lines.extend(_format_argument_section(positional_lines, is_options=False))
    else:
        lines.append("None.")

    lines.extend(["", "## Optional Arguments", ""])
    if option_lines:
        lines.extend(_format_argument_section(option_lines, is_options=True))
    else:
        lines.append("None.")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    cur_dir = pathlib.Path(__file__).parent

    parser = argparse.ArgumentParser(
        description="Generate docs pages for C2PO commands and CLI options."
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=cur_dir / "../docs/user/commands.md",
        help="Path to output Markdown file (default: %(default)s)",
    )
    parser.add_argument(
        "--options-output",
        type=pathlib.Path,
        default=cur_dir / "../docs/user/options.md",
        help="Path to output options Markdown file (default: %(default)s)",
    )
    args = parser.parse_args()

    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote C2PO command reference to {output_path}")

    options_output_path = args.options_output.resolve()
    options_output_path.parent.mkdir(parents=True, exist_ok=True)
    options_output_path.write_text(build_options_markdown(), encoding="utf-8")
    print(f"Wrote C2PO CLI options reference to {options_output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
