[env]
R2U2_MAX_OUTPUT_VERDICTS = { value = "256", force = true }
R2U2_MAX_OUTPUT_CONTRACTS = { value = "256", force = true }
R2U2_MAX_SPECS = { value = "256", force = true }
R2U2_MAX_SIGNALS = { value = "256", force = true }
R2U2_MAX_ATOMICS = { value = "256", force = true }
R2U2_MAX_BZ_INSTRUCTIONS = { value = "512", force = true }
R2U2_MAX_TL_INSTRUCTIONS = { value = "512", force = true }
R2U2_TOTAL_QUEUE_SLOTS = { value = "4096", force = true }