#!/bin/bash
# This file was generated by Cursor AI on 2025-01-15.
#
# Script to process all .equiv files in a directory using c2po.py
# Usage: ./process_equiv_files.sh <equiv_dir> <output_dir>

set -e  # Exit on error

# Check arguments
if [ $# -ne 2 ]; then
    echo "Usage: $0 <equiv_dir> <output_dir>"
    echo "  equiv_dir:  Directory containing .equiv files"
    echo "  output_dir: Directory where output files will be written"
    exit 1
fi

EQUIV_DIR="$1"
OUTPUT_DIR="$2"

# Validate equiv directory exists
if [ ! -d "$EQUIV_DIR" ]; then
    echo "Error: Equiv directory does not exist: $EQUIV_DIR"
    exit 1
fi

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
C2PO_SCRIPT="$SCRIPT_DIR/../../c2po.py"

# Process each .equiv file
for equiv_file in "$EQUIV_DIR"/*.equiv; do
    # Check if any .equiv files exist
    if [ ! -f "$equiv_file" ]; then
        echo "Warning: No .equiv files found in $EQUIV_DIR"
        exit 0
    fi
    
    base_name=$(basename "$equiv_file" .equiv)
    output_file="$OUTPUT_DIR/${base_name}.smt2"
    
    temp_script=tmp_script.cmd
    cat > "$temp_script" <<EOF
parse_equiv $equiv_file
type_check
write_equiv_smt_encoding $output_file uflia
EOF

    echo "Processing $equiv_file -> $output_file"
    python3 "$C2PO_SCRIPT" -s "$temp_script"
    rm "$temp_script"
done

echo "Done processing all .equiv files from $EQUIV_DIR"
echo "Output files written to $OUTPUT_DIR"
