name: Regression Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install Z3
      run: |
        mkdir -p deps/
        cd deps/
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.15.0/z3-4.15.0-x64-glibc-2.39.zip
        unzip z3-4.15.0-x64-glibc-2.39.zip
        echo `pwd`/z3-4.15.0-x64-glibc-2.39/bin/ >> "$GITHUB_PATH"

    - name: Install Egglog
      run: |
        mkdir -p deps/
        cd deps/
        git clone https://github.com/egraphs-good/egglog.git
        cd egglog
        git checkout v0.4.0
        cargo build --bin egglog --release
        echo `pwd`/target/release >> "$GITHUB_PATH"
      
    - name: Build R2U2
      run: |
        cd monitors/c
        make

    - name: Build R2U2_CLI
      run: |
        cd monitors/rust/r2u2_cli
        cargo build --release

    - name: Test c2po
      run: |
        cd compiler/test
        python3 test.py

    - name: Test cav (c implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor c --r2u2 ../monitors/c/build/r2u2 cav

    - name: Test long-trace (c implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor c --r2u2 ../monitors/c/build/r2u2 long_trace

    - name: Test ft-subset (c implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor c --r2u2 ../monitors/c/build/r2u2 ft_subset

    - name: Test ft-pt-test (c implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor c --r2u2 ../monitors/c/build/r2u2 regression


    - name: Test cav (rust implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli cav

    - name: Test long-trace (rust implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli long_trace

    - name: Test ft-subset (rust implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli ft_subset

    - name: Test ft-pt-test (rust implementation)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../compiler/c2po.py --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli regression

    - name: Test cav (rust implementation with rust c2po)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../monitors/rust/r2u2_cli/target/release/r2u2_cli --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli cav

    - name: Test long-trace (rust implementation with rust c2po)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../monitors/rust/r2u2_cli/target/release/r2u2_cli --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli long_trace

    - name: Test ft-subset (rust implementation with rust c2po)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../monitors/rust/r2u2_cli/target/release/r2u2_cli --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli ft_subset

    - name: Test ft-pt-test (rust implementation with rust c2po)
      run: |
        cd test/
        python3 r2u2test.py --c2po ../monitors/rust/r2u2_cli/target/release/r2u2_cli --monitor rust --r2u2 ../monitors/rust/r2u2_cli/target/release/r2u2_cli regression